### ISSUE TITLE
remove redundant pre-commit workflow

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.srmise#106]

**Comment by bobleesj** [comment]
<img width="684" alt="Screenshot 2024-10-05 at 12 57 41 PM" src="https://github.com/user-attachments/assets/95a664b2-d33b-4bbc-a9e1-3c99d1f4fa71">

would you be referring to these red messages above?

**Comment by sbillinge** [comment]
No, this is done. Close as completed
