### ISSUE TITLE
release of diffpy.srmise to pypi

### ISSUE THREAD

**Issue by sbillinge** [diffpy/diffpy.srmise#108]
@Ainamacar I want to release the current version of diffpy.srmise to pypi, but it seems that you already have it up there, so I will need you to add me as a maintainer.  my pypi username is `sbillinge`.

Would it be possible for you to do that?  Thanks so much!

**Comment by sbillinge** [comment]
@Ainamacar gentle ping on this.  It is blocking some more work we need to do, testing releases, and I think it is a 5 minute job for you Luke.  I expect you are busy with beginning of semestar (as am I), but it would be very helpful if you could do this.

**Comment by Ainamacar** [comment]
I believe I have this sorted.  My apologies for the delay.

**Comment by sbillinge** [comment]
Thanks @Ainamacar all set.  Closing as completed
