### ISSUE TITLE
conda-forge release action items

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.srmise#126]
@sbillinge would you like to have `diffpy.srmise` on conda-forge? I am asking this because pypi 0.5.2 is available and the readme has an instruction for conda install.

**Comment by sbillinge** [comment]
yes, we need this on conda

**Comment by bobleesj** [comment]
Tasks:

- [ ] fix https://github.com/diffpy/diffpy.srmise/issues/125
- [ ] release on PyPI
- [ ] submit for conda-forge recipe review
- [ ] release on conda-forge

**Comment by bobleesj** [comment]
Done! https://github.com/conda-forge/diffpy.srmise-feedstock
