### ISSUE TITLE
Ready for 0.6.1 PyPI/GitHub release

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.srmise#138]
### Release checklist for GitHub contributors

- [x] All PRs/issues attached to the release are merged. Merge https://github.com/diffpy/diffpy.srmise/pull/137
- [x] All the badges on the README are passing.
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
  missing), tutorials, and other human written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation and on the website (e.g., diffpy.org) are updated and
  tested
- [x] Successfully run any tutorial examples or do functional testing in some other way.
- [x] Grammar and writing quality have been checked (no typos).

@sbillinge Ready for release.

**Comment by sbillinge** [comment]
Nice checklist!  The build failed for some reason though....please see Actions

**Comment by bobleesj** [comment]
Build failed because setuptools does not like having `__init__.py` that are same in each folder. Created an PR here: 

https://github.com/diffpy/diffpy.srmise/pull/139

**Comment by sbillinge** [comment]
full release sent @bobleesj please check

**Comment by bobleesj** [comment]
conda-forge review requested: https://github.com/conda-forge/diffpy.srmise-feedstock/pull/3

@sbillinge

**Comment by bobleesj** [comment]
```
srmise data/Ag_nyquist_qmax30.gr --no-extract --plot
```

renders:

<img width="603" alt="Screenshot 2024-10-24 at 8 18 25 AM" src="https://github.com/user-attachments/assets/bec82b6e-4495-41ea-89c7-715a9d04bb0e">


Closing- package testing finished!
