### ISSUE TITLE
Ready for 0.7.0 PyPI/GitHub release

### ISSUE THREAD

**Issue by bobleesj** [diffpy/diffpy.srmise#145]
### Release checklist for GitHub contributors

- [x] All PRs/issues attached to the release are merged.
- [x] All the badges on the README are passing. current CI status fails because we tested against 3.10 before
- [x] License information is verified as correct. If you are unsure, please comment below.
- [x] Locally rendered documentation contains all appropriate pages, including API references (check no modules are
  missing), tutorials, and other human written text is up-to-date with any changes in the code.
- [x] Installation instructions in the README, documentation and on the website (e.g., diffpy.org) are updated and
  tested
- [x] Successfully run any tutorial examples or do functional testing in some other way.
- [x] Grammar and writing quality have been checked (no typos).

Ready for pre-release on PyPI. Tests conducted here: https://github.com/diffpy/diffpy.srmise/pull/143

- Support Python 3.13, hence bumped from 0.6.1 to 0.7.0

**Comment by bobleesj** [comment]
@sbillinge ready for pre-release

**Comment by sbillinge** [comment]
`0.7.0rc0` sent

**Comment by bobleesj** [comment]
@sbillinge ready for full `0.7.0` release

```
```
conda install -c conda-forge/label/diffpy.srmise_rc -c conda-forge diffpy.srmise
srmise data/Ag_nyquist_qmax30.gr --no-extract --plot
```

Renders well:

<img width="604" alt="Screenshot 2024-10-24 at 9 59 48 PM" src="https://github.com/user-attachments/assets/7301661e-332a-43c4-8532-4aa2eb1d524f">

**Comment by sbillinge** [comment]
@bobleesj great!  Horrible colors though, let's have an issue to use bg-mpl-stylesheets!  Give it to a newbie....

**Comment by sbillinge** [comment]
ok, `0.7.0` sent

**Comment by bobleesj** [comment]
```
conda create -n diffpy.srmise_env diffpy.srmise   
data/Ag_nyquist_qmax30.gr --no-extract --plot --range 2 3.5
```

renders

<img width="616" alt="Screenshot 2024-10-24 at 11 09 52 PM" src="https://github.com/user-attachments/assets/48d899f4-bc2b-4309-96de-717f8022b887">

Closing!

**Comment by bobleesj** [comment]
I spotted a bug with one of the tutorials, documented: https://github.com/diffpy/diffpy.srmise/issues/147

**Comment by bobleesj** [comment]
@sbillinge Before I make a new release chekclist for `0.7.1`, the only new changes would be adding Codespells and codecov without any additional functional changes. shall we still release 0.7.1?

**Comment by sbillinge** [comment]
no, let's just not.   Leave that one as already finished.
