### ISSUE TITLE
GaussianOverR object has no attribute createpeak

### ISSUE THREAD

**Issue by stevenhua0320** [diffpy/diffpy.srmise#65]
When running terminationripples, it raises error
`ideal_peaks = Peaks([pf1.createpeak(p, "pwa") for p in pars])`
                         `^^^^^^^^^^^^^^`
`AttributeError: 'GaussianOverR' object has no attribute 'createpeak'`

**Comment by Ainamacar** [comment]
I believe all calls to `createpeak()` should be replaced by calls to `actualize()` .  They all occur in very, very old tests that I evidently stopped running before this name change.  (No doubt, this was sloppy of me.)  The files are:

- baselines/base.py
- peaks/terminationripples.py
- peaks/gaussian.py
- peaks/gaussianoverr.py

Note that throughout the code, all test code in blocks like `if __name__ == '__main__':` are not vital to the functioning of SrMise itself.  In the end most of these should probably be removed as proper tests are written.

**Comment by stevenhua0320** [comment]
Closed by PR #72
